import type { Analysis, Shape, VectorDoc } from "./types";
import { rgbToHex } from "./color";

/** Trim float noise so the output reads like hand-authored geometry. */
function n(v: number): string {
  const r = Math.round(v * 1000) / 1000;
  return Object.is(r, -0) ? "0" : String(r);
}

function slug(name: string): string {
  return name.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function shapeToSvg(s: Shape, indent: string): string {
  if (s.type === "rect") {
    return `${indent}<rect x="${n(s.x)}" y="${n(s.y)}" width="${n(s.w)}" height="${n(s.h)}" fill="${s.fill}"/>`;
  }
  const pts = s.points.map((p) => `${n(p.x)},${n(p.y)}`).join(" ");
  return `${indent}<polygon points="${pts}" fill="${s.fill}"/>`;
}

/**
 * Emit the document as SVG.
 *
 * Deliberately uses `<rect>` and `<polygon>` rather than a single merged `<path>`:
 * Figma's importer maps those onto real Rectangle and Vector nodes, so every tile
 * lands as an editable object with proper width/height rather than an opaque blob.
 */
export function toSvg(
  doc: VectorDoc,
  opts: { title?: string; includeMetadata?: boolean } = {},
): string {
  const lines: string[] = [];
  const title = opts.title ?? "Tiles";

  lines.push(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${n(doc.width)}" height="${n(doc.height)}" viewBox="0 0 ${n(doc.width)} ${n(doc.height)}" shape-rendering="crispEdges">`,
  );
  lines.push(`  <title>${escapeXml(title)}</title>`);

  if (opts.includeMetadata !== false) {
    lines.push(
      `  <desc>${escapeXml(`${doc.cols}x${doc.rows} tile lattice, ${doc.palette.length} colours, ${doc.figures.length} figures`)}</desc>`,
    );
  }

  if (doc.background) {
    lines.push(
      `  <rect id="Background" width="${n(doc.width)}" height="${n(doc.height)}" fill="${doc.background}"/>`,
    );
  }

  if (doc.backgroundTiles.length > 0) {
    lines.push(`  <g id="Base-tiles" data-name="Base tiles">`);
    for (const s of doc.backgroundTiles) lines.push(shapeToSvg(s, "    "));
    lines.push(`  </g>`);
  }

  for (const fig of doc.figures) {
    lines.push(
      `  <g id="${slug(fig.name)}-${fig.id + 1}" data-name="${escapeXml(fig.name)}">`,
    );
    for (const s of fig.shapes) lines.push(shapeToSvg(s, "    "));
    lines.push(`  </g>`);
  }

  lines.push(`</svg>`);
  return lines.join("\n");
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Emit a Figma plugin script that rebuilds the document as *native* nodes.
 *
 * The SVG route is fine and usually enough, but this one guarantees the result:
 * real RectangleNodes (resizable, radius-able, not vector blobs), real
 * VectorNodes for the half-tiles, one Group per figure, and layer names that
 * survive. Paste it into the Figma plugin console, or hand it to the Figma MCP.
 */
export function toFigmaScript(doc: VectorDoc, name = "Tiles"): string {
  // Intern colours so the payload stays small even at a few thousand tiles.
  const colorIndex = new Map<string, number>();
  const colors: string[] = [];
  const idx = (hex: string) => {
    const found = colorIndex.get(hex);
    if (found !== undefined) return found;
    colorIndex.set(hex, colors.length);
    colors.push(hex);
    return colors.length - 1;
  };

  const encode = (shapes: Shape[]) => {
    const rects: number[][] = [];
    const tris: number[][] = [];
    for (const s of shapes) {
      if (s.type === "rect") {
        rects.push([
          round(s.x),
          round(s.y),
          round(s.w),
          round(s.h),
          idx(s.fill),
        ]);
      } else {
        tris.push([
          ...s.points.flatMap((p) => [round(p.x), round(p.y)]),
          idx(s.fill),
        ]);
      }
    }
    return { rects, tris };
  };

  const groups = [
    ...(doc.backgroundTiles.length
      ? [{ name: "Base tiles", ...encode(doc.backgroundTiles) }]
      : []),
    ...doc.figures.map((f) => ({ name: f.name, ...encode(f.shapes) })),
  ];

  const payload = {
    name,
    width: round(doc.width),
    height: round(doc.height),
    background: doc.background,
    colors,
    groups,
  };

  return `// Generated by Tiles Illustrator — rebuilds the mosaic as native Figma nodes.
// Run inside a Figma plugin (or hand to the Figma MCP \`use_figma\` tool).

const DOC = ${JSON.stringify(payload)};

function paint(hex) {
  const v = hex.replace('#', '');
  return {
    type: 'SOLID',
    color: {
      r: parseInt(v.slice(0, 2), 16) / 255,
      g: parseInt(v.slice(2, 4), 16) / 255,
      b: parseInt(v.slice(4, 6), 16) / 255,
    },
  };
}

const frame = figma.createFrame();
frame.name = DOC.name;
frame.resizeWithoutConstraints(DOC.width, DOC.height);
frame.fills = DOC.background ? [paint(DOC.background)] : [];
frame.clipsContent = false;

const center = figma.viewport.center;
frame.x = Math.round(center.x - DOC.width / 2);
frame.y = Math.round(center.y - DOC.height / 2);

for (const group of DOC.groups) {
  const nodes = [];

  for (const [x, y, w, h, ci] of group.rects) {
    const node = figma.createRectangle();
    node.resizeWithoutConstraints(w, h);
    node.x = x;
    node.y = y;
    node.fills = [paint(DOC.colors[ci])];
    node.strokes = [];
    node.name = DOC.colors[ci];
    frame.appendChild(node);
    nodes.push(node);
  }

  for (const tri of group.tris) {
    const ci = tri[tri.length - 1];
    const pts = [];
    for (let i = 0; i < tri.length - 1; i += 2) pts.push([tri[i], tri[i + 1]]);

    // Normalise to the triangle's own bounding box, then place the node —
    // Figma draws vector path data relative to the node origin.
    const minX = Math.min(...pts.map((p) => p[0]));
    const minY = Math.min(...pts.map((p) => p[1]));
    const data =
      'M ' +
      pts.map((p) => (p[0] - minX) + ' ' + (p[1] - minY)).join(' L ') +
      ' Z';

    const node = figma.createVector();
    node.vectorPaths = [{ windingRule: 'NONZERO', data }];
    node.x = minX;
    node.y = minY;
    node.fills = [paint(DOC.colors[ci])];
    node.strokes = [];
    node.name = DOC.colors[ci] + ' ▲';
    frame.appendChild(node);
    nodes.push(node);
  }

  if (nodes.length > 1) {
    const g = figma.group(nodes, frame);
    g.name = group.name;
  } else if (nodes.length === 1) {
    nodes[0].name = group.name;
  }
}

figma.currentPage.appendChild(frame);
figma.currentPage.selection = [frame];
figma.viewport.scrollAndZoomIntoView([frame]);
`;
}

function round(v: number): number {
  return Math.round(v * 100) / 100;
}

/** The grid model itself, for anyone who wants to drive their own renderer. */
export function toJson(analysis: Analysis, doc: VectorDoc): string {
  return JSON.stringify(
    {
      grid: { cols: analysis.cols, rows: analysis.rows },
      background: rgbToHex(analysis.background),
      palette: analysis.palette.map((c, i) => ({
        hex: rgbToHex(c),
        cells: analysis.paletteCounts[i] ?? 0,
      })),
      counts: {
        empty: analysis.emptyCount,
        square: analysis.squareCount,
        split: analysis.splitCount,
      },
      figures: doc.figures.map((f) => ({
        name: f.name,
        bounds: f.bounds,
        cells: f.cellCount,
        shapes: f.shapes.length,
      })),
      cells: analysis.cells
        .filter((c) => c.kind !== "empty")
        .map((c) =>
          c.kind === "square"
            ? { col: c.col, row: c.row, kind: "square", fill: rgbToHex(c.color) }
            : {
                col: c.col,
                row: c.row,
                kind: "split",
                diagonal: c.kind === "split" ? c.diagonal : undefined,
                first:
                  c.kind === "split" && c.first ? rgbToHex(c.first) : null,
                second:
                  c.kind === "split" && c.second ? rgbToHex(c.second) : null,
              },
        ),
    },
    null,
    2,
  );
}
